### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by salibeh** [FIWARE/tutorials.Securing-Access-OpenID-Connect#10]
Hi,

I followed the tutorial and when i got to the http://localhost:3000, i received a page that is not mentioned in your tutorial (see below).  When entered alice credentials and clicked Authorization Code, that was successful. That is I received that the login was successful and passed along the access token, etc.   However, When I tried the OpenID over Authorization Code, I received Access Denied.  

I appreciate any help in resolving this issue.  Also, it would be great if you can point me to wher I may find Keyrock logs.
Best,
Emil

**Comment by jason-fox** [comment]
Assuming your docker-compose looks like this:

```yaml
  keyrock:
    image: fiware/idm:${KEYROCK_VERSION}
    depends_on:
      - mysql-db
    ports:
      - "${KEYROCK_PORT}:${KEYROCK_PORT}" # localhost:3005
      - "${KEYROCK_HTTPS_PORT}:${KEYROCK_HTTPS_PORT}" # localhost:3443
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_DB_PASS_FILE=/run/secrets/my_secret_data
      - IDM_DB_USER=root
      - IDM_HOST=http://localhost:${KEYROCK_PORT}
      - IDM_PORT=${KEYROCK_PORT}
      - IDM_HTTPS_ENABLED=${IDM_HTTPS_ENABLED}
      - IDM_HTTPS_PORT=${KEYROCK_HTTPS_PORT}
      - IDM_ADMIN_USER=alice
      - IDM_ADMIN_EMAIL=alice-the-admin@test.com
      - IDM_ADMIN_PASS=test
```

you can view your logs with `docker logs keyrock`. It is important that the `DEBUG` environment variable is set.
