### ISSUE TITLE
services.tutorial.depends_on contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by danielvillalbamota** [FIWARE/tutorials.Securing-Access-OpenID-Connect#8]
I have found an error in the docker-compose.yml where docker-compose v3 expects a list in the tutorial.depends_on:

The current docker-compose.yml have:
```
depends_on:
    keyrock:
        condition: service_started
    orion:
         condition: service_started
```
and I have solved it with 
```
depends_on:
    - keyrock
    - orion
```
I can PR this, but I do not know if it requires maintaining the "condition" as a health check that I do not know how to implement.
